#if !canImport(ObjectiveC)
import XCTest

extension MarkpagesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MarkpagesTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MarkpagesTests.__allTests__MarkpagesTests),
    ]
}
#endif
